const githubActionTypes = {
  SET_USER_NAME: " SET_USER_NAME",
  REQUEST_USER_PENDING: "REQUEST_USER_PENDING",
  REQUEST_USER_SUCCESS: "REQUEST_USER_SUCCESS",
  REQUEST_USER_FAILED: "REQUEST_USER_FAILED"
};
export default githubActionTypes;
